### ISSUE TITLE
OpenVBX-Directory errors out if nobody answers...

### ISSUE THREAD

**Issue by nshenry03** [tjlytle/OpenVBX-Directory#1]
Everything works as expected until the user does not answer the phone...  Then the system says: 'Sorry, an error occurred.'...

I believe that it works correctly if the user picks up in time (or their voicemail picks up in time); however, it doesn't seem to work otherwise...

**Comment by tjlytle** [comment]
Thanks for the report - I'll look into it.

**Comment by nshenry03** [comment]
Hi Tim, thanks for looking into this!  Were you able to reproduce the issue on your end?  Please let me know if there's anything I can do to help.

Thanks again,
Nick Henry

**Comment by tjlytle** [comment]
Have not had a chance yet - hope to next week.

**Comment by tjlytle** [comment]
So sorry this took me this long to fix for you. It should work now.

**Comment by nshenry03** [comment]
No problem, I'll hopefully be able to give it a try later this week when
things settle down a little :-)

Thanks,

Nicholas Henry
nshenry03@gmail.com
(720) 675-9086

On Sat, Jan 14, 2012 at 7:20 PM, Tim Lytle <
reply@reply.github.com
