### ISSUE TITLE
Caller ID

### ISSUE THREAD

**Issue by Awatatah** [tjlytle/OpenVBX-Directory#2]
How do I change the call that is activated to show the correct phone number? Not the incoming caller but the openvbx phone number. Just like the "dial" applet, it gives you the option to choose caller ID

**Comment by minaevd** [comment]
When you make an outbound manual call in OPENVBX there is a drop down list of numbers to choose from - they are the Twilio phone numbers you own.
Is that what you're asking about?

**Comment by Awatatah** [comment]
No, this is regards to OpenVBX-Directory plugin only. When I select this applet, there are no options to select the caller ID. I need to be able to select the Twilio number to be shown on the caller ID not the callers number.

**Comment by minaevd** [comment]
Seems like you have to add a few lines of code, similar to those in the standard Dial applet for this functionality.

**Comment by Awatatah** [comment]
what code do I add?

**Comment by minaevd** [comment]
something like that, hope it will route you to the right direction:

# ui.php:

```
$callerId = AppletInstance::getValue('callerId', null);
...
    <br />
    <h2>Caller ID</h2>
    <div class="vbx-full-pane">
        <fieldset class="vbx-input-container">
            <select class="medium" name="callerId">
                <option value="">Caller's Number</option>
<?php if(count($numbers)) foreach($numbers as $number): $number->phone = normalize_phone_to_E164($number->phone); ?>
                <option value="<?php echo $number->phone; ?>"<?php echo $number->phone == $callerId ? ' selected="selected" ' : ''; ?>><?php echo $number->name; ?></option>
<?php endforeach; ?>
            </select>
        </fieldset>
    </div>
```

# 

# twiml.php

```
...
                $callerId = AppletInstance::getValue('callerId', null);
        if (empty($callerId) && !empty($_REQUEST['From'])) 
        {
            $callerId = $_REQUEST['From'];
        }
...
                // somewhere you respond:
                response->dial(NULL, array(
                    'action' => ...,
                    'callerId' => $callerId,
                                        ...
...
```

#

**Comment by Awatatah** [comment]
I'm having a hard time where to put your `twiml.php` code

**Comment by Awatatah** [comment]
Maybe you can put the entire code for both `ui.php` and `twiml.php` please? Thank you so much for your help.

**Comment by Awatatah** [comment]
I figured it out. I've attached the code incase anyone else wants to use this or if maintainer wants to add this feature (I recommend)

[twiml.txt](https://github.com/tjlytle/OpenVBX-Directory/files/544517/twiml.txt)
[ui.txt](https://github.com/tjlytle/OpenVBX-Directory/files/544518/ui.txt)

**Comment by tjlytle** [comment]
@Awatatah if you want to fork and make this a PR, I'd be happy to merge.

**Comment by Awatatah** [comment]
@tjlytle Done!
